name: Notify Slack on Release

on:
  workflow_run:
    workflows:
      - Release
    types: [completed]

permissions:
  contents: read
  actions: read

jobs:
  check-release:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    outputs:
      should_notify: ${{ steps.check.outputs.should_notify }}
    steps:
      - name: Check for release artifacts
        id: check
        continue-on-error: true
        run: |
          # Try to download release artifacts - if successful, a release was created
          if gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts --jq '.artifacts[] | select(.name == "release-artifacts") | .id' | grep -q .; then
            echo "should_notify=true" >> "$GITHUB_OUTPUT"
            echo "✓ Release artifacts found - a release was created"
          else
            echo "should_notify=false" >> "$GITHUB_OUTPUT"
            echo "✗ No release artifacts found - release was skipped"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

  notify:
    needs: check-release
    if: needs.check-release.outputs.should_notify == 'true'
    permissions:
      contents: read
    uses: ./.github/workflows/slack-message.yml
    secrets: inherit
    with:
      branch: ${{ github.event.workflow_run.head_branch }}
      status: ${{ github.event.workflow_run.conclusion || 'success' }}
      run-url: ${{ github.event.workflow_run.html_url || format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.event.workflow_run.id) }}
      head_sha: ${{ github.event.workflow_run.head_sha || github.sha }}
      actor: ${{ github.event.workflow_run.actor.login || github.actor }}
      repo: ${{ github.repository }}
      include-changelog: ${{ github.event.workflow_run.head_branch == 'main' }}
